window.V7Logic = (() => {
  const expressways = ['pie','cte','sle','tpe','aye','kpe','bke','ecp','mce','kje'];
  function norm(text){ return String(text||'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim(); }
  function plates(text){ return [...new Set((String(text||'').match(/\b[A-Z]{1,3}\d{1,4}[A-Z]\b/gi)||[]).map(x=>x.toUpperCase()))]; }
  function date(text){ return (String(text||'').match(/\b\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4}\b/)||[''])[0]; }
  function time(text){ const m=String(text||'').match(/(?:about\s*)?(\d{3,4})\s*hrs/i); if(!m)return''; const r=m[1].padStart(4,'0'); return r.slice(0,2)+r.slice(2)+' hrs'; }
  function road(text){ const raw=String(text||'').replace(/\b(?:on|at)?\s*\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4}\b/gi,'').replace(/\b(?:at|about)?\s*\d{3,4}\s*hrs\b/gi,''); for(const p of [/\balong\s+([^,.]+?)(?:\s+towards|\s+when|\s+while|\s+and|,|\.|$)/i,/\bat\s+([^,.]+?)(?:\s+when|\s+while|\s+and|,|\.|$)/i,/\bon\s+([^,.]+?)(?:\s+when|\s+while|\s+and|,|\.|$)/i]){ const m=raw.match(p); if(m&&m[1]&&!/^\d/.test(m[1].trim()))return m[1].trim(); } return ''; }
  function vehicleType(text,fallback){ const t=norm(text); if(t.includes('motorcycle')||t.includes('bike')||t.includes('riding'))return'Motorcycle'; if(t.includes('lorry'))return'Lorry'; if(t.includes('truck'))return'Truck'; if(t.includes('bus'))return'Bus'; if(t.includes('van'))return'Van'; if(t.includes('taxi'))return'Taxi'; return fallback||'Car'; }
  function ownPlate(text, ps){ if(!ps.length)return''; const s=String(text||''); const m=s.match(/(?:my|company|client|our)\s+(?:vehicle|car|lorry|van|bus|truck)?\s*\(?\s*([A-Z]{1,3}\d{1,4}[A-Z])\s*\)?/i)||s.match(/I\s+was\s+(?:driving|riding)(?:\s+my\s+company\s+vehicle|\s+my\s+vehicle|\s+my\s+car|\s+car|\s+vehicle|\s+lorry|\s+truck|\s+van|\s+bus|\s+motorcycle)?\s*\(?\s*([A-Z]{1,3}\d{1,4}[A-Z])/i); return m&&ps.includes(m[1].toUpperCase())?m[1].toUpperCase():ps[0]; }
  function scoreType(text){ const s=norm(text); const ps=plates(text); const unique=ps.length; const rearPhrases=['hit the rear','hit my rear','hit the back','rear ended','rear ended','collided into the rear','collided with the rear','impact from the rear','felt an impact from the rear','knocked into the rear','bumped into the rear','rammed the rear','struck the rear','approached from behind','hit from behind','knocked from behind','failed to stop in time','unable to stop in time','could not stop in time','unable to react in time','unable to avoid colliding','failed to maintain a safe following distance','safe following distance','safe distance','brake in time','braked late','front of my vehicle collided','front portion of my vehicle collided','front portion collided','front of my car collided','rear of my vehicle','rear of my car','rear of vehicle','came into contact with the rear','contact with the rear section','contact was made with the rear','made contact with the rear','rear section of my vehicle','rear portion of my vehicle','approached from the rear','unable to maintain sufficient distance','unable to avoid contact','unable to do likewise','unable to stop before reaching','front portion of my vehicle came into contact','eventually reached the rear']; let rearHit=rearPhrases.some(p=>s.includes(p));
    const rearPatterns=[/front\s+(?:portion\s+)?of\s+(?:my\s+)?(?:vehicle|car|lorry|van|truck|bus|taxi|motorcycle).{0,90}rear\s+of/i,/(?:i|my\s+(?:vehicle|car|lorry|van|truck|bus|taxi|motorcycle)).{0,100}(?:hit|collided|bumped|knocked|struck|rammed).{0,70}rear\s+of/i,/(?:failed|unable|could\s+not).{0,50}(?:stop|brake|react|avoid).{0,90}rear\s+of/i,/(?:came\s+into\s+contact|made\s+contact|contact\s+was\s+made).{0,90}rear\s+(?:section|portion|of)/i,/front\s+(?:portion\s+)?of\s+my\s+(?:vehicle|car|lorry|van|truck|bus|taxi|motorcycle).{0,120}(?:came\s+into\s+contact|made\s+contact|reached).{0,90}rear/i,/vehicle\s+behind.{0,100}(?:unable\s+to\s+maintain|contact\s+was\s+made|made\s+contact).{0,100}rear/i,/(?:unable\s+to\s+avoid\s+contact|unable\s+to\s+stop\s+before\s+reaching|unable\s+to\s+do\s+likewise)/i,/contact\s+occurred\s+at\s+(?:its|the)\s+rear/i,/(?:vehicle\s+ahead|vehicle\s+in\s+front).{0,140}(?:slowed|reduced\s+speed|lost\s+speed).{0,160}(?:my\s+|I\s+).{0,100}(?:unable|could\s+not|braked|contacted|reached|rear-end\s+contact)/i,/(?:reached\s+the\s+back\s+of\s+my|reached\s+the\s+rear\s+of\s+my|made\s+contact\s+with\s+the\s+rear\s+portion\s+of\s+my)/i,/the\s+following\s+(?:vehicle|car|lorry|van|truck|bus|taxi|motorcycle)?.{0,120}(?:contact\s+was\s+made|impact|rear\s+of\s+my|back\s+of\s+my)/i]; if(rearPatterns.some(p=>p.test(text||'')))rearHit=true;
    const chainPhrases=['chain collision','chain accident','multiple impact','secondary impact','sandwiched','causing another collision','causing my vehicle to hit','causing my vehicle to collide','pushed into the vehicle in front','pushed forward and collided','pushed forward and hit','pushed onto the vehicle in front','vehicle in front was struck']; const explicit=/\b(?:3|three|4|four|5|five|multiple)\s+vehicles?\b/.test(s); const chainHit=unique>=3&&(chainPhrases.some(p=>s.includes(p))||explicit); if(chainHit&&!(unique<=2&&rearHit))return'Chain Collision'; if(rearHit)return'Rear-End Collision'; if(['changed lane','change lane','filter into','filtering','merged','merge','cut into','swerved into','entered my lane','encroached into my lane'].some(p=>s.includes(p)))return'Lane Change'; if(['side swipe','side swiped','scraped','brushed','grazed','hit the side','side of my','left side','right side','beside me','alongside'].some(p=>s.includes(p)))return'Side Swipe'; if(s.includes('parked')||s.includes('parking'))return'Parked Vehicle'; if(s.includes('junction')||s.includes('traffic light'))return'Junction Collision'; return'Manual Review'; }
  function rearRoles(text){ const t=String(text||''); const s=norm(text); const ps=plates(text); const own=ownPlate(text,ps); const others=ps.filter(p=>p!==own); const other=others[0]||''; const lab=p=>p&&p===own?'A':p?'B':'';
    const aFrontCue=/(vehicle\s+behind|behind\s+me|travelling\s+behind|traveling\s+behind|approached\s+from\s+(?:the\s+)?rear|approached\s+from\s+behind|following\s+(?:vehicle|car|lorry|van|truck|bus|taxi|motorcycle)|reached\s+the\s+(?:back|rear)\s+of\s+my|rear\s+(?:section|portion|of)\s+my|back\s+of\s+my|contact\s+with\s+the\s+rear\s+of\s+my|contact\s+was\s+made\s+with\s+the\s+rear\s+of\s+my)/i.test(t);
    const aRearCue=/(vehicle\s+ahead|vehicle\s+in\s+front|ahead\s+slowed|ahead\s+lost\s+speed|rear\s+of\s+(?:vehicle\s+)?[A-Z]{1,3}\d{1,4}[A-Z]|contact\s+occurred\s+at\s+its\s+rear|rear-end\s+contact\s+with\s+it|front\s+(?:area|portion)\s+of\s+my|my\s+vehicle.?s\s+front\s+portion\s+reached\s+its\s+rear\s+portion|distance\s+to\s+.+?\s+ahead\s+closed)/i.test(t);
    if(aFrontCue&&!aRearCue)return{front:'A',rear:lab(other)||'B',review:false,reason:'A_front_stress_cue'}; if(aRearCue&&!aFrontCue)return{front:lab(other)||'B',rear:'A',review:false,reason:'A_rear_stress_cue'};
    const aFrontPatterns=[/(?:vehicle\s+)?(?<rear>[A-Z]{1,3}\d{1,4}[A-Z]).{0,140}(?:came\s+into\s+contact|made\s+contact|contact\s+was\s+made|impacted|collision\s+occurred|unable\s+to\s+avoid\s+contact|unable\s+to\s+stop\s+before\s+reaching|unable\s+to\s+do\s+likewise).{0,120}(?:rear\s+(?:section|portion)\s+of\s+my|rear\s+of\s+my|my\s+(?:vehicle|car|lorry|truck|van|bus|taxi|motorcycle))/i,/vehicle\s+behind.{0,120}(?:unable\s+to\s+maintain|contact\s+was\s+made|made\s+contact).{0,120}rear\s+of\s+my/i,/(approached\s+from\s+(?:the\s+)?rear|travelling\s+behind|behind\s+me).{0,120}(collision\s+occurred|impact|contact|unable\s+to)/i,/rear\s+(section|portion)\s+of\s+my\s+(vehicle|car|lorry|truck|van|bus|taxi|motorcycle)/i]; for(const p of aFrontPatterns){const m=t.match(p); if(m){let rp=(m.groups&&m.groups.rear||'').toUpperCase(); if(rp===own)rp=''; return{front:'A',rear:lab(rp||other)||'B',review:false,reason:'A_front_ambiguous_rear_contact'};}}
    const aRearPatterns=[/\bI\s+(?:had\s+)?(?:rear ended|rear-ended)\s+(?:vehicle\s+)?(?<front>[A-Z]{1,3}\d{1,4}[A-Z])?/i,/\bI\s+(?:hit|collided into|collided with|bumped into|knocked into|rammed|struck)\s+(?:the\s+)?rear\s+of\s+(?:vehicle\s+)?(?<front>[A-Z]{1,3}\d{1,4}[A-Z])?/i,/my\s+(?:vehicle|car|lorry|truck|van|bus|taxi|motorcycle).{0,100}(?:hit|collided|bumped|knocked|struck|rammed|contacted|came\s+into\s+contact|made\s+contact|reached).{0,80}rear/i,/\bI\s+(?:failed to stop|could not stop|did not manage to brake|failed to brake|braked late|was unable to stop|unable to stop|was unable to react|unable to react|was unable to avoid)\b/i]; for(const p of aRearPatterns){const m=t.match(p); if(m){let fp=(m.groups&&m.groups.front||'').toUpperCase(); return{front:lab(fp||other)||'B',rear:'A',review:false,reason:'A_rear_ended_B'};}}
    const aFrontDirect=[/\bI\s+was\s+(?:rear ended|rear-ended|hit|knocked|bumped|rammed)\s+(?:by\s+)?(?<rear>[A-Z]{1,3}\d{1,4}[A-Z])?/i,/my\s+(?:vehicle|car|lorry|truck|van|bus|taxi|motorcycle)\s+was\s+(?:rear ended|rear-ended|hit|knocked|bumped|rammed)\s+(?:by\s+)?(?<rear>[A-Z]{1,3}\d{1,4}[A-Z])?/i,/(impact from the rear|felt an impact from the rear|hit from behind|knocked from behind|approached from the rear|came into contact with the rear section of my vehicle|contact was made with the rear of my vehicle)/i]; for(const p of aFrontDirect){const m=t.match(p); if(m){let rp=(m.groups&&m.groups.rear||'').toUpperCase(); if(rp===own)rp=''; return{front:'A',rear:lab(rp||other)||'B',review:false,reason:'A_was_rear_ended_by_B'};}}
    if(/\b(rear|back|behind|bumper)\b/.test(s))return{front:'A',rear:'B',review:false,reason:'rear_end_fallback_A_front'}; return{front:'',rear:'',review:true,reason:'No reliable rear-end pattern detected'}; }
  function laneCount(text){ const s=norm(text); if(/\b(4|four)\s+lane/.test(s))return'4'; if(/\b(3|three)\s+lane/.test(s))return'3'; if(/\b(2|two)\s+lane/.test(s))return'2'; return''; }
  function analyze(text){ const p=plates(text); const type=scoreType(text); const roles=type==='Rear-End Collision'?rearRoles(text):{front:'',rear:'',review:type==='Manual Review'||type==='Chain Collision',reason:type}; const t=norm(text); return{date:date(text),time:time(text),road:road(text),road_lane_count:laneCount(text),lane_position:t.includes('right lane')?'right':t.includes('left lane')?'left':t.includes('middle lane')?'middle':'',road_feature:expressways.some(e=>t.includes(e))?'expressway':t.includes('traffic light')?'traffic_light':t.includes('junction')?'junction':t.includes('filter lane')?'filter_lane':t.includes('slip road')?'slip_road':t.includes('merging')?'merging_lane':'',accident_type_display:type,vehicle_count:type==='Chain Collision'?'3+':'2',front_vehicle:roles.front,rear_vehicle:roles.rear,vehicle1_plate:p[0]||'',vehicle1_model:'Car',vehicle2_plate:p[1]||'',vehicle2_type:vehicleType(text,'Car'),vehicle3_plate:p[2]||'',vehicle3_type:p[2]?'Car':'',manual_review:roles.review?'Yes':'No',review_reason:roles.reason}; }
  const smartTests=[['A','B','I slowed down for traffic and the vehicle behind contacted the rear of my vehicle.'],['A','B','While moving along PIE, I felt an impact at the back after the car in front slowed.'],['B','A','The front vehicle stopped suddenly and I could not avoid contact with its rear.'],['A','B','I was stationary at the traffic light when another car hit the back of my car.'],['A','B','My vehicle was knocked from behind but there were only two cars involved.'],['B','A','The car ahead braked and my front bumper touched its rear bumper.'],['A','B','I was travelling along CTE when I was hit from the rear by the following vehicle.'],['A','B','Traffic slowed and there was a bump to the back of my vehicle.'],['A','B','The vehicle behind me failed to stop in time and collided with my rear.'],['B','A','I accidentally knocked into the rear of the car in front when traffic came to a stop.'],['A','B','The following vehicle was unable to maintain sufficient distance and contact was made with the rear portion of my vehicle.'],['B','A','My vehicle continued forward and rear-end contact occurred at its rear.']];
  function runTests(){ return smartTests.map(([front,rear,statement],index)=>{ const r=analyze(statement); const pass=r.front_vehicle===front&&r.rear_vehicle===rear&&r.accident_type_display==='Rear-End Collision'&&r.vehicle_count==='2'; return{index:index+1,pass,expectedFront:front,expectedRear:rear,actualFront:r.front_vehicle,actualRear:r.rear_vehicle,statement,result:r};}); }
  return { analyze, runTests, rearEndRoles: rearRoles, isChain: t => scoreType(t)==='Chain Collision' };
})();
